<?php
$NoSQL["ERROR_API1_CF_AUTO_COMPLETE"] = 300;
$NoSQL["ERROR_API1_CF_COMMON_DYNAMIC"] = 301;
$NoSQL["ERROR_API1_CF_SEARCH"] = 302;
$NoSQL["ERROR_API1_CF_SEARCH_RELATED"] = 303;
$NoSQL["ERROR_API1_CF_SEARCH_RELATED_INDEX"] = 304;
$NoSQL["ERROR_API1_CF_AUTO_COMPLETE_INDEX"] = 305;
$NoSQL["ERROR_API1_CF_AUTO_COMPLETE_TEXT"] = 306;
$NoSQL["ERROR_API1_CF_SEARCH_INDEX"] = 307;
$NoSQL["ERROR_API1_CF_SEARCH_TEXT"] = 308;
$NoSQL["ERROR_API1_CF_AUTO_COMPLETE"] = 309;
$NoSQL["ERROR_API1_CF_COMMON_DYNAMIC"] = 310;
$NoSQL["ERROR_API1_CF_SEARCH"] = 311;
$NoSQL["ERROR_API1_CF_SEARCH_RELATED"] = 312;
$NoSQL["ERROR_API1_CF_SEARCH_RELATED_INDEX"] = 313;
$NoSQL["ERROR_API1_CF_AUTO_COMPLETE_INDEX"] = 314;
$NoSQL["ERROR_API1_CF_AUTO_COMPLETE_TEXT"] = 315;
$NoSQL["ERROR_API1_CF_SEARCH_INDEX"] = 316;
$NoSQL["ERROR_API1_CF_SEARCH_TEXT"] = 317;
?>
