<?php
use cassandra\ConsistencyLevel;
$NoSQL['SERVERS'] = array([SERVERS]);
$NoSQL['KEYSPACE_NAME'] = [KEYSPACE_NAME];
$NoSQL['READ_CONSISTENCY_LEVEL'] = [READ_CONSISTENCY_LEVEL];
$NoSQL['WRITE_CONSISTENCY_LEVEL'] = [WRITE_CONSISTENCY_LEVEL];
?>
